import streamlit as st
import torch
import torch.nn as nn
from torchvision import models
from PIL import Image
import numpy as np

# -------------------------------------------------------------------
# 1. MODEL LOADING
# We use @st.cache_resource so Streamlit loads the model into RAM
# only ONCE when the app starts, instead of on every button click.
# -------------------------------------------------------------------
@st.cache_resource
def load_model():
    # For now, we use a pre-trained ResNet50 as a placeholder.
    # Later, we will replace this with your actual trained model weights.
    model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
    
    # Replace the final layer to output 2 classes: Benign, Malignant
    num_ftrs = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(num_ftrs, 256),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(256, 2)
    )
    
    # Set model to evaluation mode
    model.eval()
    return model

model = load_model()

# -------------------------------------------------------------------
# 2. IMAGE PREPROCESSING
# This function takes the uploaded image and prepares it for the model.
# -------------------------------------------------------------------
def preprocess_image(image):
    # Convert image to grayscale
    img = image.convert('L')
    
    # Resize to 224x224 (required by ResNet)
    img = img.resize((224, 224))
    
    # Convert to numpy array and normalize to [0, 1]
    img_array = np.array(img) / 255.0
    
    # Stack the single channel 3 times to create a 3-channel image (RGB)
    # ResNet expects 3 channels, even for grayscale images.
    img_array = np.stack([img_array, img_array, img_array], axis=0)
    
    # Convert to PyTorch tensor and add a batch dimension (1, 3, 224, 224)
    img_tensor = torch.tensor(img_array, dtype=torch.float32).unsqueeze(0)
    
    return img_tensor

# -------------------------------------------------------------------
# 3. PREDICTION FUNCTION
# -------------------------------------------------------------------
def predict_mammogram(image):
    if image is None:
        return "Please upload an image."
    
    # Preprocess the image
    img_tensor = preprocess_image(image)
    
    # Run inference (disable gradient calculation for speed)
    with torch.no_grad():
        outputs = model(img_tensor)
        probs = torch.softmax(outputs, dim=1)
        predicted_class = torch.argmax(probs, dim=1).item()
        confidence = probs[0][predicted_class].item()
    
    # Format the output
    classes = ["Benign", "Malignant"]
    result_text = f"Prediction: {classes[predicted_class]}"
    confidence_text = f"Confidence: {confidence * 100:.2f}%"
    
    return result_text, confidence_text

# -------------------------------------------------------------------
# 4. STREAMLIT USER INTERFACE
# -------------------------------------------------------------------
st.set_page_config(page_title="Mammography Research System", page_icon="🩺")

st.title("🩺 Breast Mammogram Image Analysis")
st.markdown("""
**Research System Prototype**
Upload a mammogram image to receive a model prediction. 
*Note: This is a research prototype, not a clinical diagnostic tool.*
""")

# File uploader
uploaded_file = st.file_uploader("Choose a mammogram image (JPG, JPEG, PNG)...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image (FIXED LINE BELOW)
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Mammogram', use_container_width=True)
    
    st.write("---")
    
    # Add a button to trigger the prediction
    if st.button("Analyze Image"):
        with st.spinner("Analyzing mammogram..."):
            result_text, confidence_text = predict_mammogram(image)
            
            # Display results
            st.success("Analysis Complete!")
            col1, col2 = st.columns(2)
            with col1:
                st.metric(label="Model Prediction", value=result_text.split(": ")[1])
            with col2:
                st.metric(label="Confidence Score", value=confidence_text.split(": ")[1])
            
            st.info("⚠️ **Disclaimer:** This output is generated by a research prototype. It is not a medical diagnosis and should not be used for clinical decision-making.")