import streamlit as st
import torch
import torch.nn as nn
from torchvision import models
from PIL import Image
import numpy as np

# -------------------------------------------------------------------
# 1. PAGE CONFIGURATION & CUSTOM CSS
# -------------------------------------------------------------------
st.set_page_config(page_title="Mammography Research System", page_icon="🩺", layout="wide")

# Custom CSS to make the UI look professional
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        color: #1E3A8A;
        text-align: center;
        font-weight: bold;
        margin-bottom: 0px;
    }
    .sub-header {
        font-size: 1.3rem;
        color: #4B5563;
        text-align: center;
        margin-bottom: 30px;
    }
    </style>
""", unsafe_allow_html=True)

# -------------------------------------------------------------------
# 2. SIDEBAR: ACADEMIC METADATA
# -------------------------------------------------------------------
with st.sidebar:
    st.markdown("### 🎓 Research Information")
    
    st.markdown("**Research Topic:**")
    st.info("Breast Cancer Detection using Mammography: Image Processing to Deep Learning")
    
    st.markdown("**Researcher:**")
    st.write("Fatima Farouk")
    
    st.markdown("**Institution:**")
    st.write("Federal University Dutse (FUD)")
    
    st.markdown("---")
    st.markdown("### ⚙️ Model Details")
    st.write("**Architecture:** ResNet50 (Transfer Learning)")
    st.write("**Dataset:** CBIS-DDSM")
    st.write("**Framework:** PyTorch & Streamlit")

# -------------------------------------------------------------------
# 3. MAIN HEADER
# -------------------------------------------------------------------
st.markdown('<p class="main-header">🩺 Breast Mammogram Image Analysis</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">A Deep Learning Approach for Early Breast Cancer Detection</p>', unsafe_allow_html=True)

# -------------------------------------------------------------------
# 4. MODEL LOADING
# -------------------------------------------------------------------
@st.cache_resource
def load_model():
    # Placeholder model until we train the real one
    model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
    num_ftrs = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Linear(num_ftrs, 256),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(256, 2)
    )
    model.eval()
    return model

model = load_model()

# -------------------------------------------------------------------
# 5. IMAGE PREPROCESSING & PREDICTION
# -------------------------------------------------------------------
def preprocess_image(image):
    img = image.convert('L')
    img = img.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.stack([img_array, img_array, img_array], axis=0)
    img_tensor = torch.tensor(img_array, dtype=torch.float32).unsqueeze(0)
    return img_tensor

def predict_mammogram(image):
    if image is None:
        return "Please upload an image."
    
    img_tensor = preprocess_image(image)
    
    with torch.no_grad():
        outputs = model(img_tensor)
        probs = torch.softmax(outputs, dim=1)
        predicted_class = torch.argmax(probs, dim=1).item()
        confidence = probs[0][predicted_class].item()
    
    classes = ["Benign", "Malignant"]
    result_text = f"Prediction: {classes[predicted_class]}"
    confidence_text = f"Confidence: {confidence * 100:.2f}%"
    
    return result_text, confidence_text

# -------------------------------------------------------------------
# 6. MAIN UI - UPLOAD & RESULTS
# -------------------------------------------------------------------
st.markdown("---")

col1, col2 = st.columns([1, 1])

with col1:
    st.markdown("### 📤 Upload Mammogram")
    uploaded_file = st.file_uploader("Choose an image (JPG, JPEG, PNG)...", type=["jpg", "jpeg", "png"])
    
    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Mammogram', use_container_width=True)

with col2:
    st.markdown("### 📊 Analysis Results")
    if uploaded_file is not None:
        if st.button("Analyze Image", use_container_width=True):
            with st.spinner("Analyzing mammogram..."):
                result_text, confidence_text = predict_mammogram(image)
                
                st.success("Analysis Complete!")
                st.metric(label="Model Prediction", value=result_text.split(": ")[1])
                st.metric(label="Confidence Score", value=confidence_text.split(": ")[1])
                
                st.info("⚠️ **Disclaimer:** This output is generated by a research prototype. It is not a medical diagnosis and should not be used for clinical decision-making.")
    else:
        st.write("Please upload an image to see the results.")
